# Generated by Django 4.2.30 on 2026-07-31 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['parent__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'parent')},
        ),
    ]
