# Generated by Django 4.2.30 on 2026-06-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('books', '0003_book_library_genre_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksuggestion',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='libraries.library'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(blank=True, help_text='Which library owns this book', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraries.library'),
        ),
        migrations.AlterField(
            model_name='booksuggestion',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'library')},
        ),
    ]
