# Generated by Django 4.2.30 on 2026-05-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('users', '0002_user_email_verification_token_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ForeignKey(blank=True, help_text='Which library this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='libraries.library'),
        ),
    ]
